<!doctype html>
<html lang="en" class="no-js">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
!!CANONICAL!!
!!HEADER!!
	
<body>
<section class="contentarea">
	<header>
            <h1 class="head1"><span>General Rabbit Care</span> health</h1>
            
            <p><a href="#sick" id="pagelink">Is Your Rabbit Sick?</a>&nbsp;&nbsp;<b>//</b>&nbsp;&nbsp;
                <a href="#poop" id="pagelink">The Scoop on Poop</a>&nbsp;&nbsp;<b>//</b>&nbsp;&nbsp;
                <a href="#gi" id="pagelink">Rabit GI Physiology &amp; Nutrition</a>&nbsp;&nbsp;<b>//</b>&nbsp;&nbsp;
                <a href="#spay" id="pagelink">Get Your Rabbit Spayed or Neutered</a>&nbsp;&nbsp;<b>//</b>&nbsp;&nbsp;
                <a href="#emergency" id="pagelink">EMERGENCY</a>
        </header>

	<span class="anchor" id="sick"></span></span>
		<h2 class="head2"><span>Is Your Rabbit Sick?</span></h2>
			<p>Rabbits are at the bottom of the food chain and in the wild the weakest are the first to be preyed upon. Thus, rabbits instinctively hide illnesses and injuries to avoid detection by animals of prey. This may be a good survival tactic in the wild, but for domestic rabbits, hiding their symptoms of illness only misleads their caretakers and prevents prompt medical attention. 
<p>People who live with rabbits need to be particularly attentive to subtle changes in behavior or litter box habits. 
<p>If your rabbit usually greets you with leaps and bounds and he is now lying in the back of the cage when you approach, this could be a cause for concern. Couple this behavior change with no droppings in his litter box and food left untouched, and you could have a very sick rabbit. 
<p>What is “normal” behavior? Some rabbits jump up to greet you; some don’t. Some rabbits are very active, running all over the house; some aren’t. In general, rabbits mellow a bit as they age. A three-month-old bunny might seem hyperactive compared to a more sedate five-year-old rabbit. Both activity levels are normal, just different. But this behavior will be consistent and known to you. Any deviation of that behavior could signal illness. 
<p>The following information is offered as a layman’s guide to some rabbit ailments. Be sure to find a rabbit-experienced veterinarian before your bunny gets sick. When your bunny is ill, you need help quickly and you won’t have time to “shop” for a vet. If you are ever in question about your rabbit’s health, call your veterinarian for advice. 
<p>Tooth grinding: Loud tooth grinding is a sure sign of pain. Note: This tooth grinding is different from the softer “tooth purring” you may hear when you snuggle and kiss Bun’s face! 
<p>Body heat: Rabbits regulate body temperature by their ears. Very cold or hot ears could indicate a fever or a drop in body temperature. This, coupled with other warning signs would warrant a trip to the vet. 
<p>Runny eyes or nose, labored breathing or chronic sneezing: These could indicate an upper respiratory infection, a blocked tear duct or other problems. See your veterinarian right away. 
<p>Wet chin or drooling: Usually a sign of tooth problems or malocclusion. You may also notice a decrease in appetite and ability to eat hard foods such as a piece of carrot. See your veterinarian. Left untreated, tooth problems can lead to infection of the jaw bone, which is very difficult to treat. Depending on the severity of the misalignment, your rabbit’s teeth may need to be trimmed regularly. In severe cases, teeth can be pulled. A wet chin can indicate malocclusion. In this case, the bunny’s front teeth needed to be pulled. 
<p>Loss of balance or a head tilt: This is most often a sign of wry neck, which is an inner ear infection. This can occur very suddenly. Although treatment can be lengthy, and improvement not noticeable for some time, wry neck may be cured if treatment is begun quickly. Editor’s note: Head tilt can also be caused by the E.Cuniculi parasite and must also be immediately treated by your veterinarian. Head tilt is usually caused by an inner ear infection or by the E.Cuniculi parasite. 
<p>Excessive itching or scratching, head shaking: Fleas, ear mites and/or fur mites are the usual culprits. In some ear mite cases, scabs can be seen in the ear canal. Your veterinarian will decide what treatment is needed. If one rabbit in your house has mites, it is best to have all the rabbits checked, as mites can be transferred easily. 
<p>Fleas are common in the summer months. Although they may seem harmless, flea infestations can kill rabbits, dogs and cats by causing a deadly case of anemia. Use a flea comb and consult your veterinarian about the use of a flea treatment such as Program or Advantage. (Do NOT use Frontline, which has been linked to rabbit deaths.) Have your carpet steam-cleaned or treated with a commercial borate-compound product to kill the flea eggs and larvae. The borate treatment is usually guaranteed for a year. Be sure the products used are safe for rabbits. (Rule of thumb: If it’s safe for kittens, it is usually safe for adult rabbits.) 
<p>** Editor's Note: An organic, non-toxic method now used is the application of Diatomaceous Earth. Learn more about it here. Be sure to use only "food grade" DE around your rabbits. 
<p>Sore hocks: This is when the fur on the rabbit’s hock, or heel, is worn down to the bare skin or, in severe cases, to the bone. Sometimes the rabbit forms calluses and gets along just fine. Problems arise when the skin turns into an open wound. You may notice the rabbit favoring a foot as he tries to avoid putting weight on his hocks. Causes are numerous, including wire cage bottoms with no resting area, a damp resting board, wet bunny beds or dirty litter boxes. Overweight and large-breed rabbits are particularly prone to sore hocks, as are the Rex breeds, since they do not have a lot of padding on their feet. 
<p>If there are open wounds on your rabbit’s hocks or if the area is swollen, see your veterinarian. To prevent sore hocks, give your rabbit a soft, clean resting area. Also, keep your rabbit’s weight within normal range, and examine your rabbit’s feet regularly. 
<p>Blood in the urine, straining to urinate: The two may or may not go hand in hand. While certain foods can turn urine red, actual blood in the urine can be a sign of cancer, bladder infection or urinary stones. If your rabbit is straining to urinate or is “leaking” puddles outside the litter box, you should be concerned. You may also notice “urine burn,” caused when urine-soaked fur keeps the skin underneath damp and irritated. This is a serious health issue, so take your rabbit to his veterinarian. 
<p>In one end, out the other: Your rabbit’s litter box contains a wealth of information. A healthy digestive tract will produce large, round fecal pellets. Increasingly smaller, irregularly shaped droppings or droppings strung together with fur (or carpet) may indicate a problem. Proper grooming by you, especially during a molt, and plenty of fresh hay will help produce optimum digestive tract health, along with appealing to the rabbit’s urge to chew. If you find the litter box has no droppings in it, a vet visit is needed to see if your rabbit could have a blockage. 
<p>Lumps and bumps: Abscesses and tumors can be serious and should be checked by your veterinarian as soon as possible. Sudden “lumps” under the skin could signal serious and fast-growing cancers. 
<p>Loss of appetite or lethargy: Even a rabbit can have a “bad hare day.” But if your rabbit refuses his usual fresh food or any of his special treats, and seems particularly lethargic, you should call your rabbit’s veterinarian right away. We encourage you to observe your rabbit’s behavior, activity level and droppings daily. Each rabbit is different and knowing what is normal behavior for your rabbit could save his life. 

		<span class="anchor" id="poop"></span>
			<h2 class="head2"><span>The Scoop on Poop</span></h2>
			<p>Cecal pellets (aka cecotropes) are a special food made by bunny, just for bunny. They are partially digested foods that are passed from the bunny and then reingested. You may not see bunny do this, but when she appears to be bathing her belly and she comes up chewing, she's probably just taken up a cecal pellet. It is from these cecal pellets that a rabbit gets the majority of her nutrition, not from the first passage of food through the gut. 
<p>Unlike most other mammals, rabbits produce two types of droppings, fecal pellets (the round, dry ones you usually see in the litterbox) and cecotropes. The latter are produced in a portion of the rabbit's digestive tract called the cecum. The cecum contains a wild brew of bacteria and fungi that are normal and beneficial for the rabbit. In fact, the rabbit cannot live without them, since the cecal flora produces essential nutrients (e.g., fatty acids and vitamins) that the rabbit cannot produce on her own. 
<p>How does the rabbit get those vitamins? She eats the cecotropes as they exit the anus. Sound disgusting? Not for a rabbit. When she's enjoying her favorite, home-made snack, she'll tell you how delightful it is with that blissful, soft-eyed face and butt-twitch that signals all is well with the world. 
<p>Cecotropes are not feces. They are nutrient-packed dietary items essential to your rabbit's good health. A rabbit usually produces cecotropes at a characteristic time of the day, which may vary from rabbit to rabbit. Some produce cecotropes in the late morning, some in the late afternoon, and some at night. In any case, they usually do this when you're not watching, which might be why some people refer to cecotropes as "night droppings." 
<p>Normal Intestinal Products 
<p>Anyone who lives with a bunny has seen a FECAL PELLET. These are the small, brown "cocoa puffs" that we all hope end up mostly in the litterbox. They are round, relatively dry and friable, and composed mostly of undigested fiber. Rabbits do not ordinarily re-ingest fecal pellets, though a few bunnies seem to enjoy an occasional fecal pellet hors d'ouevre. A normal CECOTROPE resembles a dark brown mulberry, or tightly bunched grapes. It is composed of small, soft, shiny pellets, each coated with a layer of rubbery mucus, and pressed into an elongate mass. The cecotrope has a rather pungent odor, as it contains a large mass of beneficial cecal bacteria. When the bunny ingests the cecotrope, the mucus coat protects the bacteria as they pass through the stomach, then re-establish in the cecum. 

			<p><center><img src="img/scooponpoop.jpg"></center>
		<p><a href="#top" id="pagelink">back to top</a>

	<span class="anchor" id="gi"></span>
			<h2 class="head2"><span>Rabbit GI Physiology &amp; Nutrition</span></h2>
			<p>Susan A. Brown, D.V.M 
<p>Midwest Bird and Exotic Animal Hospital 
<p>Westchester, IL 60154 
<p>Rabbits are strict herbivores. Their relatively small body size makes it difficult to store large volumes of coarse fiber as might be done in the cow or horse. The gastrointestinal tract (GIT) attempts to eliminate fiber as quickly as possible. Large fiber particles stimulate motility of the GIT. The rabbit then utilizes the non-fiber portion of the food to produce the nutrients that are needed for life, some of which are absorbed directly from the GIT and some of which are reingested in the form of cecotropes. This particular system allows for a large volume of food intake, with a rapid digestive transit time thus increasing the total amount of energy stored and minimizing the need to store fiber. 
<p>Ingested food first enters the stomach, where the pH is approximately 1-2 creating very acidic environment. Preweaning rabbits have a stomach pH much closer to neutral (5-6.5) which allows bacterial flora to be initiated into the GIT. After weaning the pH drops dramatically. It is not known what the pH of the stomach is in all states of disease or anorexia and even in health the pH may not be constant. However, published research tends to support that the stomach environment is normally quite acidic. 
<p>Ingesta in the stomach is essentially sterilized, massaged a bit and broken down into smaller particles. It then moves into and through the small intestine where nutrients are extracted, and more water is added resulting in a fluid content. It may take several days for the stomach to completely empty, so fasting a rabbit to empty its GIT for diagnostic testing as in the case of radiography to detect a gastric foreign body, generally does not work. In addition, the fasting itself will slow down gut motility because the fiber which "drives" the system is not being taken in. It is not recommended to fast a rabbit prior to a surgical procedure. Rabbits do not have ability to vomit. 
<p>At the end of the small intestine is the ileocecocolonic junction. The cecum is a large blind sac in which resides a specific population of bacteria that break down digestible fiber whereas the indigestible fiber drives the GI tract and keeps things moving. Through bacterial fermentation proteins, fatty acids and certain vitamins are produced. Some of these items are directly absorbed thorough the wall of the cecum, but most are returned to the rabbit when it eats the cecotropes which are formed nutrient rich "feces" that come directly from the cecum. Hard waste feces (what is found on the floor of the cage) which have a high fiber content, are produced for approximately the first four hours after the rabbit eats its food and the cecotropes are produced during the next four hours (therefore not only at night). The cecotropes are ingested directly from the anus, have a mucous coating, are soft, moist have a stronger odor and are brighter green color that the dry waste feces. This mucous coating helps to protect the microflora through the acid pH of the stomach. The dominant bacteria in the cecum of the healthy adult rabbit is Bacteriodes with small amounts of Clostridium sp. and E. coli. Note that Lactobacillus species are not common or normal inhabitants of the adult rabbit GIT, therefore, in my opinion it makes no sense to feed products that contain Lactobacillus to our pets. In addition, unprotected live bacterial products fed to a rabbit will be destroyed in the very acid pH of the stomach. If we truly want to repopulate to GIT with healthy bacteria, we should be using the species that are normally present in health. Some practitioners have advocated giving the fresh cecotropes of healthy rabbits to ill patients. This is probably not a bad idea, but the problem is that it may be difficult to collect the cecotropes due to the fact that rabbits eat them directly and the healthy individual doesn't usually "drop" them in the cage unless they have a collar placed on them, which is stressful. If cecotropes are used, they must be retained in their "whole" form to protect their mucous coating (i.e. not ground up). Probably only 2 or 3 cecotropes are needed. 
<p>When the liquid small intestinal contents get to the area of the junction of the large intestine and cecum it enters sac-like areas in the wall of the cecum and colon called haustra which move food along by muscular contractions. When the liquid small intestinal contents reach this junction the long fibers are separated from the digestible portion of the food and moved into the center of the colon where they become the hard, dry waste feces and are passed out of the body. The digestible portion of the intestinal contents are moved into the cecum to undergo fermentation. The haustra move the liquid ingesta back and forth in the cecum and in the colon continually separating fiber from digestible particles. In fact, in the colon, water is actually excreted into the lumen to aid in the separation of fiber and non-fiber portions. The large fibers are moved towards the center of the lumen and the digestible particles accumulate along the wall in the haustra of the large intestine. These digestible particles are then are moved in a retrograde fashion back into the cecum. 
<p>There is a constant flux back and forth in the cecum and upper third of the colon to mix and separate food particles. Because it is so important to have a liquid consistency to the ingesta in this area to allow sorting of materials, it could be detrimental to administer such materials as psyillium (Metamucil) to rabbits, because these products tend to absorb moisture to create bulk and the end result may actually be constipation. 
<p>So back to diet of the HOUSE RABBIT....I want to stress that we are speaking here of the nonproduction, nonreproductive house pet specifically. We recommend feeding the house rabbit a diet that is high in fiber and relatively low in calories (especially fats and starches). Unfortunately, over the years, we have seen pelleted diets become a problem in the maintenance of the house rabbit. Pelleted diets were originally formulated for the rapid growth and ease of care of the meat or fur production rabbit, and for laboratory rabbits. Most of these rabbits were not meant to live out their full life span. The pellets perform an excellent function in these situations, as they produce rapid growth, good weight gain, are efficient, economical and easy to feed. The problem comes when we have a house rabbit that is usually neutered, is expected to live out its full life potential, and unfortunately may not get all the exercise it needs. Pelleted diets are typically made up of chopped, compressed alfalfa hay, various grains and other added nutrients. Grains can be quite high in calories (starches and fats) and usually lower in fiber than just hay. The alfalfa hay in pellets is chopped and compressed and heated and may lose some of its fiber quality. 
<p>The problems that we and other practitioners have seen over the years when pets are fed an unlimited primary pelleted diet are obesity, chronic soft stools (mixed with normal stools) and periodic bouts of anorexia (commonly known as "hairballs", but what I feel is more likely a GIT motility problem.) We have also seen less frequently, calcification of blood vessels (some pellets are quite high in calcium), and bladder and kidney stones. I am not going to say that all of these problems are entirely caused by the diet, but my observation is that diet plays a very big role. If we correct the diet, then we can attend to other factors that may be still be present. Some manufacturers of pellets have been sensitive to the needs of the house rabbit and are producing higher fiber and lower calorie pellets. Unfortunately other manufacturers have gone the opposite direction and have decided to add all kinds of dangerous things to the pellet mix such as seeds, nuts and additional grains in the name of marketing without sufficient knowledge of what the consequences can be. Regardless, I think that those of us who deal with house rabbits should not depend on pellets as the total food source for our house rabbits. 
<p>The diet that we recommend for the ADULT, NONREPRODUCTIVE HOUSE RABBIT (and we did not "originate" this, there are plenty of practitioners around who have done this for years) is no more than 1/8 cup/4 lbs. of body weight of a high fiber maintenance type pellet (18% or higher fiber) per day. (Some adult animals are given no pellets at all if they have trouble losing weight or have chronic GIT problems). In young growing animals the pellets may be given free choice until they are about 6-8 months of age, then cut back to the maintenance amount. Fresh hay should be offered FREE CHOICE throughout the pet's life. THIS IS THE MOST IMPORTANT PART OF THIS DIET AND MUST BE AVAILABLE ALL THE TIME. Young bunnies should be exposed to hay as soon as they can eat on their own. Mixed grass hay or timothy hay is the preferred type because it is lower in calcium and calories than alfalfa hay. Try contacting a horse barn or feed store for your source. If you have three or more bunnies, just buy a bale and store it in a cool dry place, because you will use it up quickly! If you cannot get the grass hay, then use alfalfa, but be cautioned that it is much higher in calories, and calcium. I prefer that rabbits on 100% alfalfa hay not get pellets at all, because it is somewhat redundant. 
<p>We also like for our bunnies to get greens and lots of them. We pick the tough fibrous greens which are rich in a variety of nutrients. We suggest feeding a minimum of 3 types daily in a total MINIMUM total amount (of all types of greens together) of 1 heaping cup/4 lbs. body weight. Note, that this is a minimum, because as the bunny adjusts to it more can be fed. By feeding several types of greens daily, you will provide a variety of nutrients as well as not creating a finicky rabbit. Some of the excellent greens are kale, collards, beet tops, carrot tops, parsley, dandelion greens, mustard greens, romaine lettuce, broccoli leaves, Brussels sprouts, outer cabbage leaves, raspberry leaves, peppermint leaves, escarole, endive, raddichio, wheat grass, alfalfa sprouts, etc. Don't feed light colored greens (i.e. iceberg and bibb lettuce) or the mixed gourmet greens in a bag as the only source. Other vegetables such as carrots, pea pods (not the peas), green pepper, squash, can be fed. Stay away from starchy foods such as legumes (beans and peas) and corn and other grains. Fruit can also be fed with some restrictions. Stay with high fiber fruits such as apples, pears, peaches, papaya, pineapple, and strawberries, but stay away from sugary fruits such as bananas and grapes. The fruit and vegetables we feed in the amounts of 1 -2 Tablespoon/4 lbs. body weight daily. 
<p>Do not feed grains such as oats, corn, wheat, crackers, Cheerios, bread, crackers, pasta, etc. There is research to suggest that high starch and low fiber diets may be two of the contributing factors to often fatal cases of enterotoxemia. Enterotoxemia can be caused by changes in cecal pH resulting in the overgrowth of certain bacteria that produce dangerous iota toxins that when absorbed into the body ultimately lead to death. I know the bunnies love this stuff and in small amounts, and in adult rabbits it wouldn't normally be a problem, but often clients overdo and it may result in serious GIT disease. We have seen rabbits that continued to have periodic soft stools when all else was corrected about the diet, yet they still got two crackers a day. When the crackers were removed, the stools returned to normal. 
<p>For obese rabbits and those that have that chronic intermittent soft stool mixed with normal stool, I take them entirely off of pellets and feed only hay free choice for two weeks. Then I will add back in some greens and then eventually try them on small amounts of pellets. Obviously, you must make sure that the rabbit is eating hay before embarking on this diet, or else it might starve. In addition the bunny should have a thorough physical examination and diagnostic tests, if appropriate, to rule out other disorders prior to starting this diet. Removing all the pellets from the diet sounds drastic, but it works well and the bunnies seem happier and more lively as the GIT starts to work more normally again. I have had clients tell me about complete personality changes (for the better usually) when we got the weight off their pets or got rid of those soft stools that stick all over the fur and make the rabbits and the owner miserable. Some rabbits can never go back on pellets again, because the soft stools may return or the weight goes back up. In addition, rabbits that have renal or bladder stones will also be taken off pellets and alfalfa hay for life to help reduce the calcium intake. 
<p>I feel that it is a mistake to "fast" rabbits for long periods each day to reduce weight, as in the cases where rabbits may be given pellets for only a certain amount of time a day. This leaves the pet with nothing to do physiologically and mentally for long hours. In an animal that was designed to eat large amounts of food frequently it can be frustrating and stressful. In addition, I fear that it may lead to a sluggish GIT due to lack of stimulation. These pets will frequently start eating paper, wood and anything else they can get their teeth on the stave off their cravings. How often have you seen the pet that has stopped eating pellets, but eats all the newspaper in the cage? These pets are usually not on unlimited (or usually any) hay or greens and are craving fiber. 
<p>Practitioners worry that if we take the rabbits off the pellets, they will not get all the nutrients, vitamins and minerals that they are supposed to get. Remember, that the rabbit manufactures its own rich supply of nutrients in the cecum in the form of the cecotropes, because they were designed to be able to live off of a "poor" quality diet in the wild. I have not yet able to detect nutritional deficiencies on the diet we recommend and we have been recommending it for at least 5 years. In addition I rarely see a case of "hairball" on this diet. The cases of "hairball" that we see in the practice are on a primary pellet diet with little or no hay or greens. In my opinion, "hairballs" are an accumulation of ingesta an hair that takes place over time due to low GIT motility, until it reaches such a size that the rabbit stops eating. Treatment for this problem is aimed primarily at correcting the underlying dietary problems. 
<p>As far as other supplements.... There has been a lot of talk about using enzymes, and bacteria, etc. I think that these things do no harm, but are not necessary when the pet in put on a more "natural" diet. I used to recommend some of these items myself, no longer because I do not see the need to do so. I would like to see those people who are using these products first make the diet changes as suggested in this article and then be able to quantitatively document that the addition of the other "supplements" made any difference in the appearance or behavior of their pet. I certainly have been proven wrong before, but I feel more scientific research needs to be done on these various supplements to really determine if they are making a difference. 
<p>I will stress that there are a wide variety of diseases that can affect the rabbit and certainly they are not all going to be cured by a diet change. There must be a thorough physical examination and appropriate diagnostic testing performed prior to any drastic life style change for the pet. 
<p>Let's feed our pets the way they were designed to eat..lots of food with high fiber content. When they can "fill up" on hay and greens, many of them lose interest in chewing up paper and furniture (although they never lose interest in electrical cords). Let them out to exercise also, to get the weight off, keep it off and keep all the body's systems in good working order. 
<p>References: 
<p>Cheeke P. Rabbit Feeding and Nutrition. Orlando, FL. 1989. 
<p>Jenkins JR, Brown SA. A Practitioners Guide to Rabbits and Ferrets. American Animal Hospital Association, 1993. (Part of the Professional Library Series). 
<p>Reprinted with permission 

		<p><a href="#top" id="pagelink">back to top</a>

	<span class="anchor" id="spay"></span>
		<h2 class="head2"><span>Get Your Rabbit Spayed or Neutered</span></h2>
			<p>Yes! Your rabbit does need to be spayed or neutered. 
<p>There are several reasons why you should get your rabbit altered. 
1) Curb rabbit overpopulation: Rabbits are the third most relinquished animal to shelters and humane societies. Every day, rabbits are found dumped along roads, in parks, condo communities, or out in the wild. Backyards abound with pet rabbits continually reproducing because they were bought from a pet store or breeder and never altered. Hundreds of rabbits die in shelters, each day, because there are not enough homes for them all. 
<p>Breeding your rabbit - even once - takes away homes from wonderful bunnies waiting in shelters for their "forever" home. For every baby bunny born, a shelter rabbit loses its chance at life. 
<p>2) Improve behavior: Rabbits are prey animals meant to reproduce quickly and often. Therefore, they are extremely hormone-driven. They also are territorial animals that mark their territory with urine and feces. Out in the wild this is necessary behavior. Inside your home, this is no fun at all. Spaying or neutering your rabbit will curb these behaviors, along with hormonal aggression, false pregnancies and nesting, and "humping" everything in sight. A rabbit who has been spayed or neutered becomes calmer, cleaner, and more easy to handle. 
<p>3) Prevent reproductive cancers: Female rabbits are highly prone to reproductive cancers, with nearly 70% over the age of three years suffering from mammary gland or uterine tumors that spread to other organs of the body and end in a very sad and painful death. Vets can surgically remove tumors but if not caught VERY early, the cancer can continue to spread causing more tumors and leading to an early death. There is no cure for cancer in rabbits; the best you can do is buy them time with expensive surgeries or radiation therapies. Best to get your bunny altered when they are young and prevent this horrible end. By the way, male rabbits also can get testicular cancer and many an older male rabbit is found with enlarged, tumor encrusted testicles. 
<p>4) Facilitates litter box training: A rabbit who is not continually marking territory is easier to litter box train. You'll be surprised at how quickly your rabbit will pick up on using her litter box once she gets spayed. 
<p>San Diego House Rabbit Society has set up a rebate program for those individuals who get their rabbit altered. We will send you a check of $25 for a neuter, or $40 for a spay. This is for residents of San Diego and southwest Riverside counties, served by those shelters we support. To get your rebate, send a copy of your receipt (from the veterinarian performing the procedure) and include the following information: 
<p>Your Name
<p>Your Rabbit(s) Name
<p>Your Address, including street, city, and zip code
<p>Your Email Address
<p>Your Telephone Number
<p>Mail this information to:
<p>SDHRS SPAY/NEUTER REBATE FUND, 4807 Mercury Street, Suite A, San Diego, CA 92111

<p>Checks are mailed out twice a month. You may submit a maximum of four (4) receipts at one time. 

<p>**Note: Donations are gratefully accepted to support this program. If you'd like to support the spay/neuter of domestic rabbits living in San Diego and southwest Riverside counties, make a donation to our Spay/Neuter Fund. Click on "Donations" to learn how. 


		<p><a href="#top" id="pagelink">back to top</a>

<span class="anchor" id="emergency"></span>
		<h2 class="head2"><span>EMERGENCY</span></h2>
		<P>The biggest indicator that your rabbit is in need of emergency medical care is a loss of appetite and lethargy. 

		<p>Even a rabbit can have a “bad hare day,” but if your rabbit refuses his usual fresh food or any of his special treats, and seems particularly lethargic, you should call your rabbit’s veterinarian right away. We encourage you to observe your rabbit’s behavior, activity level and droppings daily. Each rabbit is different and knowing what is normal behavior for your rabbit could save his life. 

		<p>Other signs of emergency include loss of balance, seizures, low body temperature (ears should not be cold to the touch), and audible tooth grinding. 

		<p>If your rabbit is experiencing any of these symptoms, he or she should be given emergency medical care as soon as possible. Please refer to our vet list to find a rabbit savvy vet. 


      
</div>
						</div>

						

						</div>
					</div>
				</div>
			</section>
!!FOOTER!!
</body>
</html>